package TablesDto;
// Generated 10-Feb-2016 14:44:17 by Hibernate Tools 4.3.1



/**
 * Chittyusers generated by hbm2java
 */
public class Chittyusers  implements java.io.Serializable {


     private ChittyusersId id;
     private Chitties chitties;
     private Users users;
     private Integer latePaymentFee;

    public Chittyusers() {
    }

	
    public Chittyusers(ChittyusersId id, Chitties chitties, Users users) {
        this.id = id;
        this.chitties = chitties;
        this.users = users;
    }
    public Chittyusers(ChittyusersId id, Chitties chitties, Users users, Integer latePaymentFee) {
       this.id = id;
       this.chitties = chitties;
       this.users = users;
       this.latePaymentFee = latePaymentFee;
    }
   
    public ChittyusersId getId() {
        return this.id;
    }
    
    public void setId(ChittyusersId id) {
        this.id = id;
    }
    public Chitties getChitties() {
        return this.chitties;
    }
    
    public void setChitties(Chitties chitties) {
        this.chitties = chitties;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Integer getLatePaymentFee() {
        return this.latePaymentFee;
    }
    
    public void setLatePaymentFee(Integer latePaymentFee) {
        this.latePaymentFee = latePaymentFee;
    }




}


