package TablesDto;
// Generated 10-Feb-2016 14:44:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chitties generated by hbm2java
 */
public class Chitties  implements java.io.Serializable {


     private Integer chittyId;
     private String chittyName;
     private int chittyStatus;
     private Date openingDate;
     private Date closingDate;
     private int term;
     private int termUnit;
     private int remainingTerm;
     private Set<Chittyusers> chittyuserses = new HashSet<Chittyusers>(0);

    public Chitties() {
    }

	
    public Chitties(String chittyName, int chittyStatus, Date openingDate, Date closingDate, int term, int termUnit, int remainingTerm) {
        this.chittyName = chittyName;
        this.chittyStatus = chittyStatus;
        this.openingDate = openingDate;
        this.closingDate = closingDate;
        this.term = term;
        this.termUnit = termUnit;
        this.remainingTerm = remainingTerm;
    }
    public Chitties(String chittyName, int chittyStatus, Date openingDate, Date closingDate, int term, int termUnit, int remainingTerm, Set<Chittyusers> chittyuserses) {
       this.chittyName = chittyName;
       this.chittyStatus = chittyStatus;
       this.openingDate = openingDate;
       this.closingDate = closingDate;
       this.term = term;
       this.termUnit = termUnit;
       this.remainingTerm = remainingTerm;
       this.chittyuserses = chittyuserses;
    }
   
    public Integer getChittyId() {
        return this.chittyId;
    }
    
    public void setChittyId(Integer chittyId) {
        this.chittyId = chittyId;
    }
    public String getChittyName() {
        return this.chittyName;
    }
    
    public void setChittyName(String chittyName) {
        this.chittyName = chittyName;
    }
    public int getChittyStatus() {
        return this.chittyStatus;
    }
    
    public void setChittyStatus(int chittyStatus) {
        this.chittyStatus = chittyStatus;
    }
    public Date getOpeningDate() {
        return this.openingDate;
    }
    
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }
    public Date getClosingDate() {
        return this.closingDate;
    }
    
    public void setClosingDate(Date closingDate) {
        this.closingDate = closingDate;
    }
    public int getTerm() {
        return this.term;
    }
    
    public void setTerm(int term) {
        this.term = term;
    }
    public int getTermUnit() {
        return this.termUnit;
    }
    
    public void setTermUnit(int termUnit) {
        this.termUnit = termUnit;
    }
    public int getRemainingTerm() {
        return this.remainingTerm;
    }
    
    public void setRemainingTerm(int remainingTerm) {
        this.remainingTerm = remainingTerm;
    }
    public Set<Chittyusers> getChittyuserses() {
        return this.chittyuserses;
    }
    
    public void setChittyuserses(Set<Chittyusers> chittyuserses) {
        this.chittyuserses = chittyuserses;
    }




}


