package TablesDto;
// Generated 10-Feb-2016 14:44:17 by Hibernate Tools 4.3.1



/**
 * ChittyusersId generated by hbm2java
 */
public class ChittyusersId  implements java.io.Serializable {


     private int userId;
     private int chittyId;

    public ChittyusersId() {
    }

    public ChittyusersId(int userId, int chittyId) {
       this.userId = userId;
       this.chittyId = chittyId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getChittyId() {
        return this.chittyId;
    }
    
    public void setChittyId(int chittyId) {
        this.chittyId = chittyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChittyusersId) ) return false;
		 ChittyusersId castOther = ( ChittyusersId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getChittyId()==castOther.getChittyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getChittyId();
         return result;
   }   


}


