package TablesDto;
// Generated 10-Feb-2016 14:44:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Useraccounts generated by hbm2java
 */
public class Useraccounts  implements java.io.Serializable {


     private UseraccountsId id;
     private Accounts accounts;
     private Users users;
     private double creditInterestRate;
     private int creditInterestTerm;
     private Integer creditInterestCalculationTerm;
     private double debitInterestRate;
     private Integer debtInterestTerm;
     private Integer debtInterestCalculationTerm;
     private int accStatus;
     private Date openingDate;
     private Date closingDate;

    public Useraccounts() {
    }

	
    public Useraccounts(UseraccountsId id, Accounts accounts, Users users, double creditInterestRate, int creditInterestTerm, double debitInterestRate, int accStatus, Date openingDate, Date closingDate) {
        this.id = id;
        this.accounts = accounts;
        this.users = users;
        this.creditInterestRate = creditInterestRate;
        this.creditInterestTerm = creditInterestTerm;
        this.debitInterestRate = debitInterestRate;
        this.accStatus = accStatus;
        this.openingDate = openingDate;
        this.closingDate = closingDate;
    }
    public Useraccounts(UseraccountsId id, Accounts accounts, Users users, double creditInterestRate, int creditInterestTerm, Integer creditInterestCalculationTerm, double debitInterestRate, Integer debtInterestTerm, Integer debtInterestCalculationTerm, int accStatus, Date openingDate, Date closingDate) {
       this.id = id;
       this.accounts = accounts;
       this.users = users;
       this.creditInterestRate = creditInterestRate;
       this.creditInterestTerm = creditInterestTerm;
       this.creditInterestCalculationTerm = creditInterestCalculationTerm;
       this.debitInterestRate = debitInterestRate;
       this.debtInterestTerm = debtInterestTerm;
       this.debtInterestCalculationTerm = debtInterestCalculationTerm;
       this.accStatus = accStatus;
       this.openingDate = openingDate;
       this.closingDate = closingDate;
    }
   
    public UseraccountsId getId() {
        return this.id;
    }
    
    public void setId(UseraccountsId id) {
        this.id = id;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public double getCreditInterestRate() {
        return this.creditInterestRate;
    }
    
    public void setCreditInterestRate(double creditInterestRate) {
        this.creditInterestRate = creditInterestRate;
    }
    public int getCreditInterestTerm() {
        return this.creditInterestTerm;
    }
    
    public void setCreditInterestTerm(int creditInterestTerm) {
        this.creditInterestTerm = creditInterestTerm;
    }
    public Integer getCreditInterestCalculationTerm() {
        return this.creditInterestCalculationTerm;
    }
    
    public void setCreditInterestCalculationTerm(Integer creditInterestCalculationTerm) {
        this.creditInterestCalculationTerm = creditInterestCalculationTerm;
    }
    public double getDebitInterestRate() {
        return this.debitInterestRate;
    }
    
    public void setDebitInterestRate(double debitInterestRate) {
        this.debitInterestRate = debitInterestRate;
    }
    public Integer getDebtInterestTerm() {
        return this.debtInterestTerm;
    }
    
    public void setDebtInterestTerm(Integer debtInterestTerm) {
        this.debtInterestTerm = debtInterestTerm;
    }
    public Integer getDebtInterestCalculationTerm() {
        return this.debtInterestCalculationTerm;
    }
    
    public void setDebtInterestCalculationTerm(Integer debtInterestCalculationTerm) {
        this.debtInterestCalculationTerm = debtInterestCalculationTerm;
    }
    public int getAccStatus() {
        return this.accStatus;
    }
    
    public void setAccStatus(int accStatus) {
        this.accStatus = accStatus;
    }
    public Date getOpeningDate() {
        return this.openingDate;
    }
    
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }
    public Date getClosingDate() {
        return this.closingDate;
    }
    
    public void setClosingDate(Date closingDate) {
        this.closingDate = closingDate;
    }




}


