package TableDtos;
// Generated Feb 10, 2016 3:20:31 PM by Hibernate Tools 4.3.1



/**
 * ChittyUsersId generated by hbm2java
 */
public class ChittyUsersId  implements java.io.Serializable {


     private int userId;
     private int chittyId;

    public ChittyUsersId() {
    }

    public ChittyUsersId(int userId, int chittyId) {
       this.userId = userId;
       this.chittyId = chittyId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getChittyId() {
        return this.chittyId;
    }
    
    public void setChittyId(int chittyId) {
        this.chittyId = chittyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChittyUsersId) ) return false;
		 ChittyUsersId castOther = ( ChittyUsersId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getChittyId()==castOther.getChittyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getChittyId();
         return result;
   }   


}


