package TableDtos;
// Generated Feb 10, 2016 3:20:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChittyTransactions generated by hbm2java
 */
public class ChittyTransactions  implements java.io.Serializable {


     private Integer chittyTransactionId;
     private int chittyNo;
     private Integer userId;
     private Integer chtyTermNo;
     private Date date;
     private Double amount;
     private String description;
     private String transRefence;
     private Integer transStatus;
     private Date clearanceDate;
     private Integer paymentMethod;

    public ChittyTransactions() {
    }

	
    public ChittyTransactions(int chittyNo) {
        this.chittyNo = chittyNo;
    }
    public ChittyTransactions(int chittyNo, Integer userId, Integer chtyTermNo, Date date, Double amount, String description, String transRefence, Integer transStatus, Date clearanceDate, Integer paymentMethod) {
       this.chittyNo = chittyNo;
       this.userId = userId;
       this.chtyTermNo = chtyTermNo;
       this.date = date;
       this.amount = amount;
       this.description = description;
       this.transRefence = transRefence;
       this.transStatus = transStatus;
       this.clearanceDate = clearanceDate;
       this.paymentMethod = paymentMethod;
    }
   
    public Integer getChittyTransactionId() {
        return this.chittyTransactionId;
    }
    
    public void setChittyTransactionId(Integer chittyTransactionId) {
        this.chittyTransactionId = chittyTransactionId;
    }
    public int getChittyNo() {
        return this.chittyNo;
    }
    
    public void setChittyNo(int chittyNo) {
        this.chittyNo = chittyNo;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getChtyTermNo() {
        return this.chtyTermNo;
    }
    
    public void setChtyTermNo(Integer chtyTermNo) {
        this.chtyTermNo = chtyTermNo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTransRefence() {
        return this.transRefence;
    }
    
    public void setTransRefence(String transRefence) {
        this.transRefence = transRefence;
    }
    public Integer getTransStatus() {
        return this.transStatus;
    }
    
    public void setTransStatus(Integer transStatus) {
        this.transStatus = transStatus;
    }
    public Date getClearanceDate() {
        return this.clearanceDate;
    }
    
    public void setClearanceDate(Date clearanceDate) {
        this.clearanceDate = clearanceDate;
    }
    public Integer getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }




}


