package TableDtos;
// Generated Feb 10, 2016 3:20:31 PM by Hibernate Tools 4.3.1



/**
 * UserAccountsId generated by hbm2java
 */
public class UserAccountsId  implements java.io.Serializable {


     private int userId;
     private int accountId;

    public UserAccountsId() {
    }

    public UserAccountsId(int userId, int accountId) {
       this.userId = userId;
       this.accountId = accountId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserAccountsId) ) return false;
		 UserAccountsId castOther = ( UserAccountsId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getAccountId()==castOther.getAccountId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getAccountId();
         return result;
   }   


}


